---
# -------------------------------------------------------
# THEME: Deploy "Neon Pulse" (Vaporwave/Cyberpunk)
# -------------------------------------------------------

# 1. Create the Theme Directory
- name: Create Neon Pulse theme directory
  ansible.builtin.file:
    path: /var/www/wordpress/wp-content/themes/neon-pulse
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

# 2. Create style.css (The Visuals)
- name: Create Theme Stylesheet (Vaporwave CSS)
  ansible.builtin.copy:
    dest: /var/www/wordpress/wp-content/themes/neon-pulse/style.css
    owner: www-data
    group: www-data
    mode: '0644' # Ensure this is readable by the web server
    content: |
      /*
      Theme Name: Neon Pulse
      Author: Ansible
      Description: Vaporwave/Cyberpunk aesthetic with centered layout.
      Version: 2.0
      */

      @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Rajdhani:wght@300;500&display=swap');

      body {
          margine: 0;
          padding: 0;
          background-color: #050011;
          /* Vaporwave Grid Background Effect */
          background-image: 
              linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 255, 255, 0.05) 50%),
              linear-gradient(90deg, rgba(255, 0, 255, 0.06), rgba(255, 0, 255, 0.03));
          background-size: 100% 4px, 60px 100%;
          color: #e0e0e0;
          font-family: 'Rajdhani', sans-serif;
          font-size: 18px;
          text-align: center; /* Center text globally */
      }

      /* Main Centering Container */
      .main-container {
          max-width: 900px;
          margin: 60px auto;
          padding: 40px;
          background: rgba(20, 20, 35, 0.8); /* Glassmorphism */
          border: 2px solid #ff00ff;
          box-shadow: 0 0 20px #ff00ff, inset 0 0 20px rgba(0, 255, 255, 0.2);
          backdrop-filter: blur(5px);
          border-radius: 10px;
      }

      /* Neon Typography */
      h1, h2, h3 {
          font-family: 'Orbitron', sans-serif;
          text-transform: uppercase;
          letter-spacing: 3px;
          margin-bottom: 20px;
      }

      h1 {
          color: #00f3ff; /* Cyan */
          text-shadow: 0 0 10px #00f3ff, 0 0 20px #00f3ff;
          font-size: 3em;
          border-bottom: 2px solid #ff00ff;
          padding-bottom: 20px;
      }

      h2 a {
          color: #ff00ff; /* Magenta */
          text-decoration: none;
          text-shadow: 0 0 8px #ff00ff;
          transition: all 0.3s ease;
      }

      h2 a:hover {
          color: #fff;
          text-shadow: 0 0 15px #ff00ff, 0 0 30px #ff00ff;
      }

      /* Post Styling */
      article {
          margin-bottom: 50px;
          padding-bottom: 30px;
          border-bottom: 1px dashed #00f3ff;
      }

      p {
          line-height: 1.8;
          font-size: 1.2rem;
      }

      /* Image Styling */
      img {
          max-width: 100%;
          height: auto;
          border: 2px solid #00f3ff;
          box-shadow: 5px 5px 0px #ff00ff; /* Offset border style */
          margin: 20px 0;
      }

      /* Form Elements (Inputs & Buttons) */
      input[type="text"], input[type="email"], textarea {
          background: #0a0a12;
          border: 1px solid #00f3ff;
          color: #00f3ff;
          padding: 15px;
          width: 80%; /* Centered input width */
          margin-bottom: 20px;
          font-family: 'Orbitron', sans-serif;
          box-shadow: 0 0 5px rgba(0, 243, 255, 0.5);
          text-align: center;
      }

      input[type="submit"], button {
          background: linear-gradient(45deg, #ff00ff, #00f3ff);
          border: none;
          color: #fff;
          padding: 15px 40px;
          font-size: 1.2rem;
          font-family: 'Orbitron', sans-serif;
          cursor: pointer;
          text-transform: uppercase;
          box-shadow: 0 0 15px rgba(255, 0, 255, 0.6);
          transition: transform 0.2s;
      }

      input[type="submit"]:hover {
          transform: scale(1.05);
          box-shadow: 0 0 25px rgba(0, 243, 255, 0.8);
      }

      /* Footer */
      footer {
          margin-top: 50px;
          font-size: 0.9rem;
          color: #888;
          text-shadow: none;
      }

# 3. Create index.php (The Structure)
- name: Create Theme Template (index.php)
  ansible.builtin.copy:
    dest: /var/www/wordpress/wp-content/themes/neon-pulse/index.php
    owner: www-data
    group: www-data
    mode: '0644'
    content: |
      <!DOCTYPE html>
      <html <?php language_attributes(); ?>>
      <head>
          <meta charset="<?php bloginfo( 'charset' ); ?>">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title><?php wp_title( '|', true, 'right' ); ?></title>
          <link rel="stylesheet" href="<?php echo get_stylesheet_uri(); ?>">
      </head>
      <body>
          <div class="main-container">
              <header>
                  <h1><?php bloginfo('name'); ?></h1>
                  <p style="color: #ff00ff; letter-spacing: 2px;">// <?php bloginfo('description'); ?> //</p>
              </header>

              <div style="margin: 40px 0;">
                  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
                      <article>
                          <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
                          <div class="content">
                              <?php the_content(); ?>
                          </div>
                      </article>
                  <?php endwhile; else : ?>
                      <p>SYSTEM_ERROR: NO_DATA_FOUND</p>
                  <?php endif; ?>
              </div>

              <footer>
                  <p>EST. <?php echo date("Y"); ?> | VAPORWAVE_SYSTEMS_LTD</p>
              </footer>
          </div>
          <?php wp_footer(); ?>
      </body>
      </html>

# 4. Activate the New Theme
- name: Activate Neon Pulse Theme
  ansible.builtin.command: wp theme activate neon-pulse --path=/var/www/wordpress
  become_user: www-data
  changed_when: true